#!/usr/bin/env bash

action=$1
version=$2

ART_ETC=/etc/opt/jfrog/artifactory
SERVICE_INIT_FILE="/etc/init.d/artifactory"
SERVICE_SYSTEMD_FILE="/lib/systemd/system/artifactory.service"
SERVICE_TYPE=""
TIMESTAMP=$(echo "$(date '+%T')" | tr -d ":")
CURRENT_TIME="$(date '+%Y%m%d').$TIMESTAMP"

if [ "$action" = "configure" ]; then
    echo "Adding the artifactory service to auto-start..."
    awk -F/ '$2 == "docker"' /proc/self/cgroup | read
    DOCKER_VERIFICATION=$?
    systemctl -h > /dev/null 2>&1
    if [[ $? -eq 0 ]] && [[ ${DOCKER_VERIFICATION} -gt 0 ]] ; then
        # File SERVICE_INIT_FILE exists, backup the file...
        if [ -e ${SERVICE_INIT_FILE} ]; then
            mv ${SERVICE_INIT_FILE} ${SERVICE_INIT_FILE}.disabled
        fi

        # Update systemd artifactory.service with actual pid file location on upgrade to keep existing location
        pidfile=$(grep ARTIFACTORY_PID ${ART_ETC}/default | awk '{print $2}' | awk -F '=' '{print $2}')
        # Check if the PIDFile needs to be updated
        if ! grep "${pidfile}" ${SERVICE_SYSTEMD_FILE} > /dev/null; then
            echo "Updating ${SERVICE_SYSTEMD_FILE} with current PIDFile value (${pidfile})"
            cp -f ${SERVICE_SYSTEMD_FILE} ${ART_ETC}/artifactory.service.backup.${CURRENT_TIME}
            echo "Saved old ${SERVICE_SYSTEMD_FILE} as ${ART_ETC}/artifactory.service.backup.${CURRENT_TIME}"
            sed -i "s,^PIDFile=.*,PIDFile=${pidfile},g" ${SERVICE_SYSTEMD_FILE}
        fi

        systemctl daemon-reload &>/dev/null
        systemctl enable artifactory.service &>/dev/null
        SERVICE_TYPE="systemd"
    else
        # File $SERVICE_SYSTEMD_FILE exists, removing...
        if [ -e ${SERVICE_SYSTEMD_FILE} ]; then
            rm -f ${SERVICE_SYSTEMD_FILE}
        fi
        /usr/sbin/update-rc.d artifactory defaults &>/dev/null
        echo -e " DONE"
        SERVICE_TYPE="init.d"
    fi
    echo
    echo -e "\033[33m************ SUCCESS ****************\033[0m"
    echo -e "\033[33mThe Installation of Artifactory has completed successfully.\033[0m"
    echo
    echo "PLEASE NOTE: It is highly recommended to use Artifactory with an external database (MySQL, Oracle, Microsoft SQL Server, PostgreSQL, MariaDB). For details about how to configure the database, refer to https://www.jfrog.com/confluence/display/RTF/Configuring+the+Database"
    echo
    if [ ${SERVICE_TYPE} == "init.d" ]; then
        echo "You can now check installation by running:"
        echo "> service artifactory check (or $SERVICE_INIT_FILE check)"
        echo
        echo "Then activate artifactory with:"
        echo "> service artifactory start (or $SERVICE_INIT_FILE start)"
    fi
    if [ ${SERVICE_TYPE} == "systemd" ]; then
        echo "Start Artifactory with:"
        echo "> systemctl start artifactory.service"
        echo
        echo "Check Artifactory status with:"
        echo "> systemctl status artifactory.service"
    fi
fi

exit 0
