#!/usr/bin/env bash

action=$1
version=$2

echo post uninstall [[name]] \$1 = $1 >>/tmp/rpminst

if [ "$action" == "remove" ] || [ "$action" == "purge" ]; then
  # It's an un-installation
  rm -rf [[target_artifactory_home]]/work [[target_artifactory_home]]/temp 2>/dev/null

  if [ "$action" == "purge" ]; then
    echo "Purging artifactory"
    rm -rf [[target_etc_artifactory]] [[target_artifactory_home]] [[target_tomcat_home]]/webapps [[target_tomcat_home]]/work [[target_artifactory_install]]
  fi

  # check if artifactory user exists (in case another user was the default)
  getent passwd [[username]] > /dev/null 2&>1
  if [ $? -eq 0 ]; then
    echo "Logging off user [[username]]"
    /usr/bin/pkill -KILL -u [[username]] 2>&1 1>/dev/null
    echo "Removing local user [[username]]"
    /usr/sbin/userdel [[username]] 2>/dev/null || echo $?
    EXISTING_GROUP="$(grep [[group_name]] /etc/group | awk -F ':' '{ print $1 }' 2>/dev/null)"
    if [ "$EXISTING_GROUP" == "[[group_name]]" ]; then
        echo "Removing group [[group_name]]"
        /usr/sbin/groupdel [[group_name]] 2>/dev/null
    fi
  fi

    echo
    echo -e "\033[33mUninstallation of Artifactory completed\033[0m"
fi
exit 0