#!/usr/bin/env bash

action=$1
version=$2

if [ "$action" == "remove" ]; then
  # It's an un-installation

  CURRENT_USER=$(id -nu)
  if [ "$CURRENT_USER" != "root" ]; then
    echo
    echo "ERROR: Please un-install Artifactory using root."
    echo
    exit 1
  fi

  SERVICE_FILE="/etc/init.d/artifactory"

  if [ -f ${SERVICE_FILE} ]; then
    SERVICE_STATUS="$(${SERVICE_FILE} status)"
    if [[ ! "$SERVICE_STATUS" =~ .*[sS]topped.* ]]; then
      echo "Stopping the artifactory service..."
      ${SERVICE_FILE} stop || exit $?
    fi
    echo -n "Removing the artifactory service from auto-start..."
    /usr/sbin/update-rc.d -f artifactory remove 2>&1 1>/dev/null
    rm -f ${SERVICE_FILE} 2>/dev/null
    if [ -f ${SERVICE_FILE}.disabled ]; then
        rm -f ${SERVICE_FILE}.disabled 2>/dev/null
    fi
    echo -e " DONE"
  fi

  SERVICE_SYSTEMD_FILE="/etc/systemd/system/artifactory.service"

  if [ -f ${SERVICE_SYSTEMD_FILE} ]; then
    SERVICE_STATUS="$(systemctl status artifactory.service)"
    if [[ ! "$SERVICE_STATUS" =~ .*[sS]topped.* ]]; then
      echo "Stopping the artifactory service..."
      systemctl stop artifactory.service || exit $?
    fi
    echo -n "Removing the artifactory service from auto-start..."
    systemctl disable artifactory.service 2>&1 1>/dev/null
    if [ -f ${SERVICE_SYSTEMD_FILE} ]; then
        rm -f ${SERVICE_SYSTEMD_FILE} 2>/dev/null
    fi
    echo -e " DONE"
  fi

  #echo "Removing the artifactory service from auto-start"
  #/sbin/chkconfig --del artifactory 2>/dev/null

  # remove user defined as ARTIFACTORY_USER in default configuration file
  username=$(grep ARTIFACTORY_USER [[target_etc_artifactory]]/default | awk '{print $2}' | awk -F '=' '{print $2}')
  group_name=$(grep ARTIFACTORY_USER [[target_etc_artifactory]]/default | awk '{print $2}' | awk -F '=' '{print $2}')
  getent passwd ${username} 2>&1 1>/dev/null
  if [ $? == 0 ]; then
    echo "Logging off user ${username}"
    /usr/bin/pkill -KILL -u ${username} 2>&1 1>/dev/null
  fi
  echo "Removing local user ${username}"
  ( grep -q ${username} /etc/passwd &&
  /usr/sbin/userdel ${username} 2>/dev/null) || echo $?
  EXISTING_GROUP="`grep ${group_name} /etc/group | awk -F ':' '{ print $1 }' 2>/dev/null`"
  if [ "$EXISTING_GROUP" == "${group_name}" ]; then
    echo "Removing group ${group_name}"
    /usr/sbin/groupdel ${group_name} 2>/dev/null
  fi

  # Create backups
  TIMESTAMP=$(echo "$(date '+%T')" | tr -d ":")
  CURRENT_TIME="$(date '+%Y%m%d').$TIMESTAMP"
  BACKUP_DIR="[[target_var_dir]]/artifactory.backup.${CURRENT_TIME}"
  echo "Creating a backup of the artifactory home folder in ${BACKUP_DIR}"

  # ignore any failures or the package will be left in an inconsistent state
  mkdir -p "${BACKUP_DIR}" && \
  cp -a [[target_etc_dir]] "${BACKUP_DIR}/etc" && \
  mv [[target_artifactory_home]]/logs "${BACKUP_DIR}/logs" 2>&1 1>/dev/null

  if [ -d "[[target_artifactory_home]]/data" ]; then
    rm -rf "[[target_artifactory_home]]/data/tmp" 2>&1 1>/dev/null
    rm -rf "[[target_artifactory_home]]/data/work" 2>&1 1>/dev/null

    if [ $(stat -c "%d" [[target_artifactory_home]]/data/) -eq $(stat -c "%d" ${BACKUP_DIR}) ]; then
      echo "Backup [[target_artifactory_home]]/data to ${BACKUP_DIR}/data"
      cp -a [[target_artifactory_home]]/data "${BACKUP_DIR}/data" 2>/dev/null
    else
      echo "PLEASE NOTE: Skipped creating a backup of the Artifactory data folder because source and target are not in the same drive [[[target_artifactory_home]]/data, ${BACKUP_DIR}/data/]"
      cp -pr [[target_artifactory_home]]/data ${BACKUP_DIR}/data
    fi
  fi

  if [ -e [[target_tomcat_home]]/lib/mysql-connector-java*.jar ]; then
    echo "MySQL connector found"
    cp [[target_tomcat_home]]/lib/mysql-connector-java* "${BACKUP_DIR}" 2>/dev/null
  fi
  if [ -e [[target_artifactory_home]]/backup ]; then
    mv [[target_artifactory_home]]/backup "${BACKUP_DIR}/backup" 2>/dev/null
  fi
fi

exit 0
